# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BCCI_SYSTEM_DATABASE.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSettings
from PyQt5.QtWidgets import QTableWidget
from PyQt5.QtWidgets import QApplication, QMainWindow, QTableWidget, QTableWidgetItem
import mysql.connector

class Ui_otherWindow(object):

    def showMysqlDatabase(self):
        connect = mysql.connector.connect(host="localhost", user="root", password="", database="bcci_system")
        query = "SELECT * FROM employee"
        cur = connect.cursor()
        cur.execute(query)
        records = cur.fetchall()
        self.tableWidget.insertRow(0)

        for row_number, row_data in enumerate(records):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

        connect.close()

    def LOAD_DATA(self):
        connect = mysql.connector.connect(host="localhost", user="root", password="", database="bcci_system")
        cur = connect.cursor()
        cur.execute("SELECT * FROM employee") 
        rows = cur.fetchall()
        self.tableWidget.setRowCount(len(rows))
        self.tableWidget.setColumnCount(len(rows[0]))
        for i, row in enumerate(rows):
            for j, val in enumerate(row):
                item = QTableWidgetItem(str(val))
                self.tableWidget.setItem(i, j, item)

        connect.close()

    def setupUi(self, otherWindow):
        otherWindow.setObjectName("otherWindow")
        otherWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(otherWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 11, 781, 401))
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.Refresh = QtWidgets.QPushButton(self.centralwidget)
        self.Refresh.setGeometry(QtCore.QRect(10, 420, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Refresh.setFont(font)
        self.Refresh.setObjectName("Refresh")
        self.Refresh.clicked.connect(self.LOAD_DATA)
        #self.Refresh.clicked.connect(self.REFRESH)
        otherWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(otherWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        otherWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(otherWindow)
        self.statusbar.setObjectName("statusbar")
        otherWindow.setStatusBar(self.statusbar)

        self.retranslateUi(otherWindow)
        QtCore.QMetaObject.connectSlotsByName(otherWindow)

    def retranslateUi(self, otherWindow):
        _translate = QtCore.QCoreApplication.translate
        otherWindow.setWindowTitle(_translate("otherWindow", "MySqlDatabase"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("otherWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("otherWindow", "Name_of_Employee"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("otherWindow", "Name_of_Company"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("otherWindow", "Income_Tax"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("otherWindow", "Monthly_Salary"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("otherWindow", "SSS_Contribution"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("otherWindow", "Pag_Ibig"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("otherWindow", "PhilHealth"))
        self.Refresh.setText(_translate("otherWindow", "Refresh"))
